# Generated by Django 2.2.28 on 2024-11-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['creatade_date']},
        ),
    ]
