# Generated by Django 4.2 on 2024-12-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img', models.ImageField(default='default.jpg', upload_to='blog/')),
                ('status', models.BooleanField(default=False)),
                ('cuntent_view', models.IntegerField(default=0)),
                ('publish_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('categore', models.ManyToManyField(to='blog.categore')),
            ],
        ),
    ]
